name: 提交文件  # 避免项目长时间不更新导致工作流失效

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # 每天UTC时间22:30，即北京时间6:30

jobs:
  TiebaSignIn:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 确保获取所有历史记录，以便能够推送到现有分支

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 1.8

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-


    - name: Update last_run.txt
      run: |
        echo "Last run at $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')" >> last_run.txt
        git config user.name "yangyibufeng"
        git config user.email "1134456853@qq.com"  # 使用自定义的邮箱地址
        git add last_run.txt
        git commit -m "Update last_run.txt with current date and time [skip ci]" || true  # 如果没有变化则不提交
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master  # 使用GITHUB_TOKEN进行认证
