# 每天6:30执行
# UTC 时间，北京时间需要 UTC+8
name: 贴吧自动签到

on:
   workflow_dispatch:
   schedule:
       - cron: '30 22 * * *' # 每天UTC时间22:30，即北京时间6:30

jobs:
  TiebaSignIn:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0 # 确保获取所有历史记录，以便能够推送到现有分支
          
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 1.8
        
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven
      env:
        BDUSS: ${{ secrets.BDUSS }}
        SCKEY: ${{ secrets.SCKEY }}
      run: |
        mvn compile exec:java -Dexec.mainClass="top.srcrs.Run" -Dexec.args="${BDUSS} ${SCKEY}"
   
   
